<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Concerns\HandlesCrudData;
use App\Models\ActivityLog;
use App\Models\Store;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\View\View;

class StoreController extends Controller
{
    use HandlesCrudData;

    /** Render the stores listing page */
    public function index(): View
    {
        return view('stores.index', ['states' => Store::US_STATES]);
    }

    /** Return paginated, searchable store data as JSON.
     *  Global users (Super-Admin, or any custom global role) see every store;
     *  store users only see the stores they are assigned to. */
    public function data(Request $request): JsonResponse
    {
        $query = Store::query();

        if (! auth()->user()->globalRole()) {
            $query->whereHas('users', function ($q) {
                $q->where('user_id', auth()->id());
            });
        }

        return $this->paginatedResponse($request, $query, ['name', 'city'], 'stores');
    }

    /** Create a new store (slug is auto-generated by the model) */
    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'street' => 'required|string|max:255',
            'suite' => 'nullable|string|max:100',
            'city' => 'required|string|max:100',
            'state' => ['required', 'string', 'size:2', Rule::in(array_keys(Store::US_STATES))],
            'zip_code' => ['required', 'string', 'max:10', 'regex:/^[0-9]+$/'],
            'country' => 'required|string|max:100',
            'is_active' => 'boolean',
        ], [
            'zip_code.regex' => 'Zip code can only contain numbers.',
        ]);

        $store = Store::create([...$validated, 'created_by' => auth()->id()]);

        ActivityLog::record('store.created', $store, "Created store {$store->name}");

        return response()->json(['message' => 'Store created successfully', 'store' => $store]);
    }

    /** Permissions are per-store. The `can:` gate validated the permission against
     *  the user's CURRENT context store, so a store user may only mutate THAT exact
     *  store — never another store they happen to belong to with a lesser role.
     *  Global users (Super-Admin, or any custom global role) span every store. */
    private function ensureStoreAccessible(Store $store): void
    {
        if (auth()->user()->globalRole()) {
            return;
        }

        // Must be acting inside the target store's own context (switching enforces
        // membership, so the current store is always one the user belongs to).
        abort_unless((int) session('current_store_id') === $store->id, 404);
    }

    /** Update an existing store (scoped — see ensureStoreAccessible) */
    public function update(Request $request, Store $store): JsonResponse
    {
        $this->ensureStoreAccessible($store);

        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'street' => 'required|string|max:255',
            'suite' => 'nullable|string|max:100',
            'city' => 'required|string|max:100',
            'state' => ['required', 'string', 'size:2', Rule::in(array_keys(Store::US_STATES))],
            'zip_code' => ['required', 'string', 'max:10', 'regex:/^[0-9]+$/'],
            'country' => 'required|string|max:100',
            'is_active' => 'boolean',
        ], [
            'zip_code.regex' => 'Zip code can only contain numbers.',
        ]);

        $store->update($validated);

        ActivityLog::record('store.updated', $store, "Updated store {$store->name}");

        return response()->json(['message' => 'Store updated successfully', 'store' => $store]);
    }

    /** Delete a store and detach all user associations (scoped — see ensureStoreAccessible) */
    public function destroy(Store $store): JsonResponse
    {
        $this->ensureStoreAccessible($store);

        // Transaction: detach + delete land together or not at all.
        DB::transaction(function () use ($store) {
            $store->users()->detach();
            $store->delete();
        });

        ActivityLog::record('store.deleted', null, "Deleted store {$store->name}");

        return response()->json(['message' => 'Store deleted successfully']);
    }

    /** Switch the session to a different store context */
    public function switch(Request $request)
    {
        $request->validate(['store_id' => 'required|exists:stores,id']);
        $user = auth()->user();

        if ($user->isSuperAdmin()) {
            abort(403, 'Super Admins cannot switch into a store directly. Use "Log in as" to access a store as one of its assigned users.');
        }

        if (! $user->stores()->wherePivot('store_id', $request->store_id)->exists()) {
            abort(403, 'You do not belong to this store.');
        }
        session(['current_store_id' => $request->store_id]);

        $store = Store::find($request->store_id);
        ActivityLog::record('store.switched', $store, "Switched into store {$store->name}");

        // Land in the newly-selected store's dashboard context (both the selector
        // and the dashboard route here after a switch).
        return redirect()->route('dashboard')->with('status', 'Store switched.');
    }
}
